
- name: Create systemd service
  template:
    src: templates/csirtg-docker.service.j2
    dest: /etc/systemd/system/csirtg-docker.service
    owner: root
    group: root
    mode: 0644

- name: Create environment file
  template:
    src: templates/csirtg-cef.env.j2
    dest: /etc/csirtg-cef.env
    owner: root
    group: root
    mode: 0644

- name: Start the csirtg-cef service
  systemd:
    state: restarted
    name: csirtg-docker
    daemon_reload: yes
